
platform :ios, '8.0'
use_frameworks!
target 'chatDemo' do
    pod 'JSONModel', '~> 1.2.0'
    pod 'AFNetworking', '~> 2.6'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SDWebImage', '~> 3.7.6'
    pod 'Masonry', '~> 1.0.0'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'DateTools', '~> 1.7.0'
    pod 'IQKeyboardManager', '~> 4.0.3'
    pod 'HyphenateFullSDK'
    pod 'LECropPictureViewController', '~> 0.1'
    pod 'FMDB', '~> 2.6.2'
    pod 'LBXScan', '~> 1.1.1'
    pod 'ZXingObjC', '~> 3.0'
    pod 'iAppInfos', '~> 0.2.1'
    pod 'SFHFKeychainUtils', '~> 0.0.1'
    #pod 'CrashlyticsLumberjack', '~> 2.0.5'
     pod 'CocoaLumberjack', '~> 2.3.0'
    pod 'CCLogSystem', '~> 1.0.1'
    pod 'ImagePiker', '~> 0.1.0'
     pod 'Bugly', '~> 2.4.0'
end
